version: '3.3'

services:

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_links_data
      - MYSQL_ROOT_PASSWORD=link1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=link1234
      - PMA_HOST=mysql
    ports:
      - 8080:80